/* MDL_LOGICO_DBamorapet: */

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_CLIENTE VARCHAR NOT NULL,
    CPF VARCHAR NOT NULL,
    ID_FUNCIONARIO_CADASTRADOR NUMERIC
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_FUNCIONARIO VARCHAR NOT NULL,
    CPF VARCHAR NOT NULL,
    TELEFONE INTEGER NOT NULL,
    E_MAIL VARCHAR,
    MATRICULA VARCHAR NOT NULL,
    ID_TIPO_FUNCIONARIO NUMERIC
);

CREATE TABLE CLIENTE_ENDERECO (
    ID_ENDERECO_CLIENTE NUMERIC AUTO_INCREMENT PRIMARY KEY,
    MUNICIPIO VARCHAR NOT NULL,
    SG_UF VARCHAR NOT NULL,
    CEP VARCHAR NOT NULL,
    ENDERECO VARCHAR NOT NULL,
    COMPLEMENTO VARCHAR,
    ID_CLIENTE NUMERIC
);

CREATE TABLE PRODUTO (
    ID_PRODUTO NUMERIC AUTO_INCREMENT PRIMARY KEY,
    DT_ENTRADA DATE NOT NULL,
    DT_VALIDADE DATE,
    NM_PRODUTO VARCHAR NOT NULL,
    VL_PRODUTO DOUBLE NOT NULL,
    QT_ESTOQUE INTEGER NOT NULL
);

CREATE TABLE TIPO_FUNCIONARIO (
    ID_TIPO_FUNCIONARIO NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_TIPO_FUNCIONARIO VARCHAR
);

CREATE TABLE FUNCIONARIO_ENDERECO (
    ID_ENDERECO_CLIENTE NUMERIC AUTO_INCREMENT PRIMARY KEY,
    MUNICIPIO VARCHAR NOT NULL,
    SG_UF VARCHAR NOT NULL,
    ENDERECO VARCHAR NOT NULL,
    CEP VARCHAR NOT NULL,
    COMPLEMENTO VARCHAR,
    ID_FUNCIONARIO NUMERIC
);

CREATE TABLE PET (
    ID_PET NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_PET VARCHAR NOT NULL,
    RACA VARCHAR,
    DT_NACIMENTO DATE,
    OBSERVACOES VARCHAR,
    ID_CLIENTE NUMERIC NOT NULL,
    ID_PET_ESPECIE NUMERIC NOT NULL
);

CREATE TABLE PET_ESPECIE (
    ID_PET_ESPECIE NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_PET_ESPECIE VARCHAR NOT NULL
);

CREATE TABLE TIPO_SERVICO (
    ID_TIPO_SERVICO NUMERIC AUTO_INCREMENT PRIMARY KEY,
    NM_TIPO_SERVICO VARCHAR NOT NULL,
    ID_TIPO_FUNCIONARIO NUMERIC
);

CREATE TABLE SERVICO (
    ID_AGENDAMENTO NUMERIC AUTO_INCREMENT PRIMARY KEY,
    DT_AGENDAMENTO DATE NOT NULL,
    HR_AGENDAMENTO TIME NOT NULL,
    ID_FUNCIONARIO_CADASTRADOR NUMERIC,
    ID_TIPO_SERVICO NUMERIC,
    ID_PET NUMERIC,
    ID_FUNCIONARIO_RESPOSANVEL NUMERIC
);

CREATE TABLE COMPRA (
    ID_COMPRA NUMERIC AUTO_INCREMENT PRIMARY KEY,
    DT_COMPRA DATE,
    VL_TOTAL DOUBLE,
    ID_FUNCIONARIO NUMERIC,
    ID_CLIENTE NUMERIC
);

CREATE TABLE CONTEM (
    ID_PRODUTO NUMERIC,
    ID_COMPRA NUMERIC,
    QT_PRODUTO_VENDIDO INTEGER NOT NULL
);
 
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_2
    FOREIGN KEY (ID_FUNCIONARIO_CADASTRADOR)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE CASCADE;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (ID_TIPO_FUNCIONARIO)
    REFERENCES TIPO_FUNCIONARIO (ID_TIPO_FUNCIONARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE CLIENTE_ENDERECO ADD CONSTRAINT FK_CLIENTE_ENDERECO_2
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE FUNCIONARIO_ENDERECO ADD CONSTRAINT FK_FUNCIONARIO_ENDERECO_2
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE PET ADD CONSTRAINT FK_PET_2
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE PET ADD CONSTRAINT FK_PET_3
    FOREIGN KEY (ID_PET_ESPECIE)
    REFERENCES PET_ESPECIE (ID_PET_ESPECIE)
    ON DELETE CASCADE;
 
ALTER TABLE TIPO_SERVICO ADD CONSTRAINT FK_TIPO_SERVICO_2
    FOREIGN KEY (ID_TIPO_FUNCIONARIO)
    REFERENCES TIPO_FUNCIONARIO (ID_TIPO_FUNCIONARIO)
    ON DELETE CASCADE;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_2
    FOREIGN KEY (ID_FUNCIONARIO_CADASTRADOR, ID_FUNCIONARIO_RESPOSANVEL)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO, ID_FUNCIONARIO)
    ON DELETE CASCADE;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_3
    FOREIGN KEY (ID_TIPO_SERVICO)
    REFERENCES TIPO_SERVICO (ID_TIPO_SERVICO)
    ON DELETE RESTRICT;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_4
    FOREIGN KEY (ID_PET)
    REFERENCES PET (ID_PET)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_2
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_3
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_1
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES PRODUTO (ID_PRODUTO)
    ON DELETE RESTRICT;
 
ALTER TABLE CONTEM ADD CONSTRAINT FK_CONTEM_2
    FOREIGN KEY (ID_COMPRA)
    REFERENCES COMPRA (ID_COMPRA)
    ON DELETE SET NULL;